CREATE TABLE IF NOT EXISTS machines (
    ipAddress VARCHAR(45) NOT NULL PRIMARY KEY,
    hostName VARCHAR(255) NULL,
    site VARCHAR(255) NULL,
    deployedComponent VARCHAR(255) NULL,
    createdOn TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updatedOn TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Support installations made before the timestamp columns were added.
ALTER TABLE machines
    ADD COLUMN IF NOT EXISTS createdOn TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS updatedOn TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
